In [1]:
#create an array
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created:\n",a)


Array created:
 [[1 2 4]
 [5 8 7]]


In [2]:
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("Array with all zeros:\n",b)

Array with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [4]:
#create an array with random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.85064992 0.5210198 ]
 [0.35640652 0.66474485]]


In [5]:
#create a sequence of integers from 0 to 30 with step 5
import numpy as np
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [6]:
#Reshaping 3*4 array to 2*2*3 array
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\nOriginal array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [7]:
#flatten array
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nflattened array:\n",flarr)



Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [8]:
#Flatten array
flarr=arr.flatten()
print("\nOriginal array:\n",arr)
print("\nFlattened array:\n",flarr)
import numpy as np
arr=np.array([[1,2,3,4],[5,4,3,7],[6,7,0,1]])
print("\nNo of dimensions:\n",arr.ndim)
print("\nshape of array:\n",arr.shape)
print("\nsize of array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nconverted array element:\n",newtype)
print("\nconverted array type:\n",newtype.dtype)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]

No of dimensions:
 2

shape of array:
 (3, 4)

size of array:
 12

Array type:
 int32

converted array element:
 [[1. 2. 3. 4.]
 [5. 4. 3. 7.]
 [6. 7. 0. 1.]]

converted array type:
 float32


In [9]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[:1,])
c=p.astype('f')
print(c)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[[1 2 3]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
